server:
  port: 9001
spring:
  datasource:
    password: afsaralam15
    url: jdbc:mysql://localhost:3306/department?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    
  application:
      name: department-service
eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
         defaultZone: http://localhost:8761/eureka/
   instance:
      hostname: localhost